spring.application.name=OsApi

spring.datasource.url=jdbc:mysql://172.16.0.30:3306/kge_osapi?createDatabaseIfNotExist=
true&serverTimezone=UTC
spring.datasource.username=ccda
spring.datasource.password=gmSenai

spring.jpa.show-sql=True
